services:
  - type: web
    name: nest-js
    runtime: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile; npx prisma generate
    startCommand: pnpm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production        
      - key: PORT
        value: 3000
  